[character]
error_symbol = "[Î»](bold #ff5555)"
success_symbol = "[Î»](bold #50fa7b)"
[hostname]
style = "bold #bd93f9"
[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[cmd_duration]
style = "bold #f1fa8c"

# Disable the package module, hiding it from the prompt completely
[battery]
disabled = true

[directory]
truncation_length = 5
style = "bold #50fa7b"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
symbol = "ï˜ "
truncation_length = 10
truncation_symbol = ""
style = "bold #ff79c6"
format = '\[[$symbol$branch]($style)\]'

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "


[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
format = '([\[$all_status$ahead_behind\]]($style))'
style = "bold #ff5555"


[conda]
symbol = "ğŸ"
format = '\[[$symbol $environment]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
format = 'via [ğŸ³ $context](blue bold)'

[custom.git_scope]
command = '''
printf "%s" \
  "$(if [ -n "$GIT_AUTHOR_NAME" ]; then echo "$GIT_AUTHOR_NAME"; else git config user.name; fi)"
'''
description = 'The currently configured Git user.{email,name}'
format = ' as [$output]($style) '
shell = ["zsh"]
style = 'blue bold'
when = 'git rev-parse --is-inside-work-tree'
